---

- name: Install vpn-server
  hosts: RHELIKE
  become: yes

  vars:
    vpn_source: https://www.softether-download.com/files/softether/v4.42-9798-rtm-2023.06.30-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.42-9798-rtm-2023.06.30-linux-x64-64bit.tar.gz
    download_folder: /app
    working_location: /usr/local/

  tasks:
  - name: Ping my servers
    ping:

  - name: Download the VPN-Server tar-file
    get_url:
      url: "{{ vpn_source }}"
      dest: "{{ download_folder }}"

  - name: Installing tar,make,gcc
    dnf:
      name:
        - tar
        - make.x86_64
        - gcc.x86_64
      state: latest

  - name: Unarchive
    unarchive:
      src: "{{ download_folder }}/softether-vpnserver-v4.42-9798-rtm-2023.06.30-linux-x64-64bit.tar.gz"
      dest: "{{ working_location }}"
      mode: '600'
      remote_src: yes

  - name: Remove *.tar
    file:
      path: "{{ download_folder }}/softether-vpnserver-v4.42-9798-rtm-2023.06.30-linux-x64-64bit.tar.gz"
      state: absent

  - name: Make - action
    make:
      chdir: "{{ working_location }}/vpnserver"

  - name: Chmod for vpncmd and vpnserver
    file:
      path:
        - "{{ working_location }}/vpncmd"
        - "{{ working_location }}/vpnserver"
      mode: '700'
